version: "3.8"
services:
  training:
    build: .
    image: mnist-training:latest
    command: python /app/training.py
    volumes:
      - ./app:/app
    
  mnist_api:
    build: .
    image: mnist-fastapi:latest
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      training:
        condition: service_completed_successfully
